parameters:
  - name: setPython
    type: boolean
    default: true

steps:
  - checkout: self
    persistCredentials: true

  - task: UsePythonVersion@0 
    inputs:
      versionSpec: '3.7'
    condition: ${{ parameters.setPython }}

  - script: |
      sudo python3 -m ensurepip
    displayName: 'Ensure pip is installed'

  - script: |
      python3 -m pip install conan
    displayName: 'Install Conan'
  

  - script: |
      cd $(Build.SourcesDirectory)
      conan create .
    displayName: 'Create Conan Package'