parameters:
  - name: setPython
    type: boolean
    default: true

steps:
  - checkout: self
    persistCredentials: true

  - task: UsePythonVersion@0 
    inputs:
      versionSpec: '3.7'
    condition: ${{ parameters.setPython }}

  - script: |
      python3 -m pip install conan
    displayName: 'Install Conan'
    condition: ${{ parameters.setPython }}
  

  - script: |
      cd $(Build.SourcesDirectory)
      conan create .
    displayName: 'Create Conan Package'
  
  - script: |
      cd $(Build.SourcesDirectory)
      conan remote add myconan https://helloadam.jfrog.io/artifactory/api/conan/conan
      conan user -p $CONAN_API_KEY -r myconan adam@smr.llc
      conan upload hobbits-cpython/3.9.1 --all --remote myconan
    env:
      CONAN_API_KEY: $(CONAN_API_KEY)
    displayName: 'Upload Conan Package'